install numpy(numerical python)

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


importing library

In [3]:
import numpy as np

In [4]:
np.version.version

'1.21.5'

creating 1d array

In [8]:
college=np.array([11,12,13,14,15])
print(college)

[11 12 13 14 15]


In [17]:
school=np.array([(13,14,15),(16,17,18)])
print(school)

[[13 14 15]
 [16 17 18]]


In [15]:
p_school=np.array([[(10,11,12),(13,14,15)],[(16,17,18),(19,20,21)]])
print(p_school)

[[[10 11 12]
  [13 14 15]]

 [[16 17 18]
  [19 20 21]]]


In [24]:
zero_array=np.zeros((9,9))
print(zero_array)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [25]:
one_array=np.ones((5,9))
print(one_array)


[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


linspace

In [26]:
lin_space=np.linspace(0,10,50)
print(lin_space)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [27]:
dob=np.array([2005,2006])
print(dob)

[2005 2006]


In [29]:
arr_ones=np.ones((2,2))
print(arr_ones)

[[1. 1.]
 [1. 1.]]


In [32]:
m_m=np.array([(18,17,19),(13,15,19)])
print(m_m)


[[18 17 19]
 [13 15 19]]


transpose operation

In [34]:
matrix_t=np.transpose(m_m)
print(matrix_t)

[[18 13]
 [17 15]
 [19 19]]


mcq
ravel()function: multi dimensions into single dimension is flatten

In [36]:
matrix_t.ravel()

array([18, 13, 17, 15, 19, 19])

In [51]:
matrix_t.reshape(2,3)
print(matrix_t)

[[18 13]
 [17 15]
 [19 19]]


In [54]:
arr_ones.resize(2,4)
print(arr_ones)

[[1. 1. 1. 1.]
 [0. 0. 0. 0.]]


In [62]:
np.random.random((2,2))


array([[0.09301522, 0.27400016],
       [0.78508314, 0.74697491]])